name: CI Pipeline

on:
  push:
    branches:
      - dev
    paths:
    - 'apache.py'
jobs:
  trigger_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # - name: Trigger Cloud Build for pytest.py
      #   if: contains(github.event.head_commit.message, 'Process_1/pytest.py')
      #   run: |
      #     gcloud builds submit . --config=cloudbuild.yaml --substitutions=_TAG=on-prem
      #   env:
      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # - name: Trigger Cloud Build for sm.py
      #   if: contains(github.event.head_commit.message, 'Process_1/sm.py')
      #   run: |
      #     gcloud builds submit . --config=cloudbuild.yaml --substitutions=_TAG=GCP-Cloud
      #   env:
      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # - name: Trigger Cloud Build for ptes.py
      #   if: contains(github.event.head_commit.message, 'Process_1/ptes.py')
      #   run: |
      #     gcloud builds submit . --config=cloudbuild.yaml --substitutions=_TAG=on-prem
      #   env:
      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
